# Generated by Django 3.0.3 on 2020-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='课程名')),
                ('class_id', models.CharField(max_length=20, verbose_name='课程编号')),
                ('study_hour', models.IntegerField(default=0, verbose_name='总学时')),
                ('study_credit', models.IntegerField(default=0, verbose_name='总学分')),
                ('introduction', models.TextField(verbose_name='课程内容简介')),
                ('a1', models.TextField(verbose_name='进度安排')),
                ('a2', models.TextField(verbose_name='考核方式')),
                ('a3', models.TextField(verbose_name='教材及参考书')),
                ('a4', models.TextField(verbose_name='主教材')),
                ('a5', models.TextField(verbose_name='参考书')),
                ('a6', models.TextField(verbose_name='合开教师')),
                ('a7', models.TextField(verbose_name='选课指导')),
                ('a8', models.TextField(verbose_name='先修要求')),
                ('a9', models.TextField(verbose_name='教师教学特色')),
                ('a10', models.TextField(verbose_name='Office Hour')),
                ('a11', models.TextField(verbose_name='成绩评定标准')),
            ],
        ),
    ]
