# Generated by Django 3.0.3 on 2020-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0002_auto_20200807_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
        migrations.AlterField(
            model_name='post',
            name='a1',
            field=models.TextField(blank=True, verbose_name='进度安排'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a10',
            field=models.TextField(blank=True, verbose_name='Office Hour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a11',
            field=models.TextField(blank=True, verbose_name='成绩评定标准'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a2',
            field=models.TextField(blank=True, verbose_name='考核方式'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a3',
            field=models.TextField(blank=True, verbose_name='教材及参考书'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a4',
            field=models.TextField(blank=True, verbose_name='主教材'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a5',
            field=models.TextField(blank=True, verbose_name='参考书'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a6',
            field=models.TextField(blank=True, verbose_name='合开教师'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a7',
            field=models.TextField(blank=True, verbose_name='选课指导'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a8',
            field=models.TextField(blank=True, verbose_name='先修要求'),
        ),
        migrations.AlterField(
            model_name='post',
            name='a9',
            field=models.TextField(blank=True, verbose_name='教师教学特色'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(default='什么信息都没有哦～', verbose_name='课程内容简介'),
        ),
    ]
