# Generated by Django 3.0.3 on 2020-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0005_auto_20200807_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='a12',
            field=models.TextField(blank=True, verbose_name='本科生课容量'),
        ),
        migrations.AddField(
            model_name='post',
            name='a13',
            field=models.TextField(blank=True, verbose_name='研究生课容量'),
        ),
        migrations.AddField(
            model_name='post',
            name='a14',
            field=models.TextField(blank=True, verbose_name='上课时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='a15',
            field=models.TextField(blank=True, verbose_name='选课文字说明'),
        ),
        migrations.AddField(
            model_name='post',
            name='a16',
            field=models.TextField(blank=True, verbose_name='课程特色'),
        ),
        migrations.AddField(
            model_name='post',
            name='a17',
            field=models.TextField(blank=True, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='post',
            name='a18',
            field=models.TextField(blank=True, verbose_name='是否二级选课'),
        ),
        migrations.AddField(
            model_name='post',
            name='a19',
            field=models.TextField(blank=True, verbose_name='实验信息'),
        ),
        migrations.AddField(
            model_name='post',
            name='a20',
            field=models.TextField(blank=True, verbose_name='重修是否占容量'),
        ),
        migrations.AddField(
            model_name='post',
            name='a21',
            field=models.TextField(blank=True, verbose_name='是否选课时限制'),
        ),
        migrations.AddField(
            model_name='post',
            name='a22',
            field=models.TextField(blank=True, verbose_name='本科文化素质课组'),
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.TextField(default='未知', verbose_name='开课院系'),
        ),
        migrations.AddField(
            model_name='post',
            name='teacher',
            field=models.TextField(default='未知', verbose_name='主讲教师'),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='课序号'),
        ),
        migrations.AlterField(
            model_name='post',
            name='study_credit',
            field=models.IntegerField(default=0, verbose_name='学分'),
        ),
    ]
