# Generated by Django 3.0.3 on 2020-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0006_auto_20200807_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teacher_id',
            field=models.IntegerField(default=0, verbose_name='教师号'),
        ),
    ]
