# Generated by Django 3.0.3 on 2020-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0007_post_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('a1', models.TextField(blank=True, verbose_name='职称')),
                ('a2', models.TextField(blank=True, verbose_name='单位')),
                ('a3', models.TextField(blank=True, verbose_name='电话')),
                ('a4', models.TextField(blank=True, verbose_name='E-Mail')),
                ('a5', models.TextField(blank=True, verbose_name='个人简介')),
                ('a6', models.TextField(blank=True, verbose_name='主要研究方向')),
                ('a7', models.TextField(blank=True, verbose_name='研究方向简介')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='教师号'),
        ),
    ]
