# Generated by Django 3.0.3 on 2020-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0008_auto_20200807_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='教师号'),
        ),
    ]
