# Generated by Django 3.0.3 on 2020-08-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0010_auto_20200807_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='class_alter_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='课序号'),
        ),
        migrations.AddField(
            model_name='post',
            name='en_introduction',
            field=models.TextField(blank=True, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='课程号'),
        ),
    ]
