# Generated by Django 3.0.3 on 2020-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0011_auto_20200807_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
