# Generated by Django 3.0.3 on 2020-08-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0012_auto_20200807_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
