# Generated by Django 3.0.3 on 2020-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0013_auto_20200807_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, default='什么信息都没有哦～', verbose_name='全文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.TextField(blank=True, default='未知', verbose_name='开课院系'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, default='什么信息都没有哦～', verbose_name='课程内容简介'),
        ),
        migrations.AlterField(
            model_name='post',
            name='study_credit',
            field=models.IntegerField(blank=True, default=0, verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='post',
            name='study_hour',
            field=models.IntegerField(blank=True, default=0, verbose_name='总学时'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teacher',
            field=models.TextField(blank=True, default='未知', verbose_name='主讲教师'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teacher_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='教师号'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(blank=True, max_length=10, verbose_name='性别'),
        ),
    ]
