# Generated by Django 3.0.3 on 2020-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0014_auto_20200807_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='study_credit',
            field=models.CharField(blank=True, default='0', max_length=20, verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='post',
            name='study_hour',
            field=models.CharField(blank=True, default=0, max_length=20, verbose_name='总学时'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teacher_id',
            field=models.CharField(blank=True, default='0', max_length=20, verbose_name='教师号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='教师号'),
        ),
    ]
