# Generated by Django 3.0.3 on 2020-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0015_auto_20200807_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommend',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='top_50',
            field=models.BooleanField(default=False),
        ),
    ]
