# Generated by Django 3.0.3 on 2020-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '热搜',
                'verbose_name_plural': '热搜',
                'ordering': ['-count'],
            },
        ),
    ]
