# Generated by Django 3.0.3 on 2020-08-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
